# Generated by Django 5.0.2 on 2024-02-28 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='author',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
