# Generated by Django 5.0.2 on 2024-02-29 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0007_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='have_access',
        ),
        migrations.DeleteModel(
            name='User_have_product',
        ),
    ]
