# Generated by Django 5.0.2 on 2024-02-29 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0009_user_have_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_have_product',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test1.product', unique=True),
        ),
    ]
