# Generated by Django 5.0.2 on 2024-02-29 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0012_remove_user_have_product_product_product_have_access_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='have_access',
        ),
    ]
