# Generated by Django 5.0.2 on 2024-02-29 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0013_remove_product_have_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='have_access',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='test1.user_have_product'),
            preserve_default=False,
        ),
    ]
