# Generated by Django 5.0.2 on 2024-02-29 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0014_product_have_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='have_access',
        ),
        migrations.AddField(
            model_name='user_have_product',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='test1.product'),
            preserve_default=False,
        ),
    ]
