# Generated by Django 5.0.2 on 2024-02-29 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0015_remove_product_have_access_user_have_product_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='product',
        ),
        migrations.AlterField(
            model_name='user_have_product',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='test1.product'),
        ),
        migrations.DeleteModel(
            name='Groupe_product',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
