# Generated by Django 5.0.2 on 2024-02-29 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0017_alter_product_max_users_alter_product_min_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='Product', max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='start_product_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 29, 18, 56, 8, 2851)),
        ),
    ]
