# Generated by Django 5.0.2 on 2024-02-29 19:00

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0018_alter_product_product_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_have_product',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='have_access',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='test1.user_have_product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='start_product_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 29, 18, 59, 57, 827695)),
        ),
    ]
