# Generated by Django 5.0.2 on 2024-02-29 19:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0019_remove_user_have_product_product_product_have_access_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='have_access',
        ),
        migrations.AlterField(
            model_name='product',
            name='start_product_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 29, 19, 2, 21, 903551)),
        ),
        migrations.AddField(
            model_name='product',
            name='have_access',
            field=models.ManyToManyField(to='test1.user_have_product'),
        ),
    ]
