# Generated by Django 5.0.2 on 2024-02-29 19:11

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0020_remove_product_have_access_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='have_access',
        ),
        migrations.AddField(
            model_name='user_have_product',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='test1.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='start_product_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 29, 19, 11, 21, 309485, tzinfo=datetime.timezone.utc)),
        ),
    ]
