# Generated by Django 5.0.2 on 2024-02-29 19:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0021_remove_product_have_access_user_have_product_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='start_product_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(default='', max_length=150)),
                ('lesson_link', models.SlugField(max_length=300, unique=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test1.product')),
            ],
        ),
    ]
