# Generated by Django 5.0.2 on 2024-02-29 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0024_user_have_groupe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupe_product',
            name='grope_users',
        ),
    ]
